old-fashioned-image-build

In https://bugs.launchpad.net/bugs/1746631 the livecd-rootfs
code began matching hostnames "lp-*" as running inside the
launchpad buildd environment.  If the hostname matches then the
mirrors are set to ftpmaster.internal.  This patch prepends
'standalone-' to the lxd container's hostname to avoid
this match.

Change container hostname to avoid buildd match in livecd-rootfs

---

old-fashioned-image-build

Don't add a default. This avoids people from making assumptions about
what series the build will be for.

Make --series parameter required.

---

old-fashioned-image-build

Via a --project option (retaining a default of ubuntu-cpc).  Fixes #7.

Make livecd-rootfs project configurable

---

old-fashioned-image-build

This means we overwrite all of livecd-rootfs not just any non upstream directories

Install livecd-rootfs before copying over local files

---

old-fashioned-image-build

Changing the hostname was included to work-around a livecd-rootfs issue where the hostname was used to set the ubuntu archive and it was setting it to ftpinternal.  That has been fixed and this can be removed.  Furthermore, at present gethostid() in cosmic libc is segfaulting presently in this environment with this set.

Remove hostname hack

---

old-fashioned-image-build

Launchpad buildd accepts multiple --image-target parameters which are
passed on to Live build via the IMAGE_TARGETS environment variable.

Support passing image targets to the builder.

---

setup-old-fashioned

Hi there,
This PR adds a script for automating the setup of the old-fashioned user's build environment. The script checks for the appropriate build environment (Xenial), adds the Canonical ppas for oldfashioned and livebuild, installs those things, and also presents some common options for installing livecd-rootfs branches (as well as facilitating installation of custom or uncommon branches).
I've tested this functionally in a lxd container running Xenial, and I've run it through flake8 and mypy linting.

Setup script

---

old-fashioned-image-build

For those days when the build succeeds (exits 0) but nothing has turned
out the way you wanted you want --no-cleanup.  With this option you
can avoid the cleanup and later drop into the build env with
'lxd exec lp-$suite-$arch bash' and try to figure out where things have
gone sideways.

Add --no-cleanup cmdline flag to allow for LXD env debugging (issue #16)

---

old-fashioned-image-build

launchpad-buildd v168 Moved /usr/share/launchpad-buildd/slavebin to
/usr/share/launchpad-buildd/bin.

Update launchpad-buildd binary paths/names (issue #20)

---

old-fashioned-image-build

I wanted to build a buildd image but couldn't, hence this PR.  I didn't want to break --minimized users so I left that and added --subproject.  You could cause problems if you specified both but I didn't think it was worth the risk to add complexity with code to make them mutually exclusive.
You can test a build with:
$ git clone git://git.launchpad.net/livecd-rootfs
$ cd livecd-rootfs
$ sudo -E ../ubuntu-old-fashioned/old-fashioned-image-build --series disco --project ubuntu-base --subproject buildd --use-chroot-cache --img_format none

Allow for alternate sub-projects and image formats

---

scripts/ubuntu-bartender/ubuntu-bartender

We're tearing down the multipass vm when finished - there's no reason for Ubuntu Old Fashioned to do any cleanup. Adding the --no-cleanup flag to save time.
Also fixing inconsistent variable name.

Some bartender optimizations and cleanup.

---

old-fashioned-image-build

Left in the old flag for backwards compatibility.

Adding a more consistent flag to set the image format.

---

setup-old-fashioned

This PR improves the setup script's handling of supported releases for cloning livecd-rootfs repositories, alleviating the need to manually manage the list whenever a new suite is released.
Also included are some general syntax and DRY improvements.

Livecd rootfs downloading

---

old-fashioned-image-build

There are two issues here. The first is the quoting around the ppa argument, which results in this command getting executed (note the quoting around the EXTRA_PPAS variable):
```
CalledProcessError: Command '['lxc', 'exec', 'lp-xenial-amd64', '--env', 'PROJECT=ubuntu-cpc', '--env', 'ARCH=amd64', '--env', 'IMAGE_TARGETS=ec2', '--env', 'SUITE=xenial', '--env', 'NOW=20190906.2041', '--env', 'IMAGEFORMAT=ext4', '--env', 'EXTRA_PPAS="cloud-images-release-managers/qemu-backports"', '--', '/bin/sh', '-c', 'cd /build && linux64 lb config']' returned non-zero exit status 1
```
That command ends with this failure (note the erroneous double quotes in the URL):
```
softwareproperties.ppa.PPAException: 'Error reading https://launchpad.net/api/1.0/~"cloud-images-release-managers/+archive/qemu-backports" …
```

Extra quotes break ppa extras argument parsing at the livecd-rootfs level.

---

old-fashioned-image-build

When building Xenial images, we must install qemu-utils from a backports PPA. Otherwise, the images don't always boot.

We need the qemu-backports packages to build xenial images properly.

---

scripts/ubuntu-bartender/ubuntu-bartender

There's no reason to upload VCS information of the dependencies of a
build. This saves close to 1GB of transfer just for livecd-rootfs!

Don't include VCS directories with dependencies

---

old-fashioned-image-build
scripts/ubuntu-bartender/ubuntu-bartender

For example, you can now download a buildd rootfs tarball from
cloud-images [1] and use that environment to build images.
1: http://cloud-images.ubuntu.com/buildd/

Specify a local buildd chroot archive to build with

---

scripts/ubuntu-bartender/ubuntu-bartender

manage-chroot script from ubuntu-archive-to has migrated to python3 [1].
As such we need to install the python3 dependencies too.
[1] https://bazaar.launchpad.net/~ubuntu-archive/ubuntu-archive-tools/trunk/revision/1305

Tools from ubuntu-archive repo have migrated to python3

---

scripts/ubuntu-bartender/ubuntu-bartender

This is useful when making changes to ubuntu-old-fashioned and
old-fashioned-image build, and you want to use those changes with a
bartender build.

Specify a local folder containing ubuntu-old-fashioned

---

old-fashioned-image-build
scripts/ubuntu-bartender/ubuntu-bartender
setup-old-fashioned

We were using ppa:launchpad/ppa, which contains unverified automatic
builds of launchpad tools. Instead, we should be using the builds from
ppa:canonical-is-sa/ubuntu/buildd, which are the tools that feed into
the production build farm.

Switch to production launchpad build tools

---

old-fashioned-image-build
scripts/ubuntu-bartender/ubuntu-bartender
setup-old-fashioned

Commit 7d2dd06 updated bartender for the py2->3 migration of ubuntutools
and launchpadlib but missed a few couple of other places that would only
be seen if running setup and builds without bartender.  This patch
migrates those to py3 dependencies as well.
Additionally the older python2 package was not removed.  That package is 
not required after the py3 migration and is dropped by these commits.

Add missing py3 deps

---

scripts/ubuntu-bartender/README.md
scripts/ubuntu-bartender/aws-provider
scripts/ubuntu-bartender/ubuntu-bartender

Providers had hardcoded values. This made configuration of the provider
a bit of a chore, for instance if you had specific keynames or profile
you wanted to use. This allows users to set some AWS provider option via
CLI or via file. Config file sourcing was added for long living options,
such as AWS_PROFILE and AWS_KEYPAIR_NAME. The addition of AWS_AMI_OWNER
and AWS_AMI_FILTER_NAME gives flexibility when testing, including
searching for an ARM base, or using an experimental base for a build (by
using a non-Canonical official OwnerID for AWS_AMI_OWNER)

Add AWS provider options and config file reading

---

README.md
scripts/ubuntu-bartender/README.md
scripts/ubuntu-bartender/ubuntu-bartender
setup-old-fashioned

The Launchpad builders are upgrading to Bionic:
> The VMs in Launchpad's build farm have been on Ubuntu 16.04 (xenial) for
some time.  We're intentionally fairly conservative about upgrading the
base VMs, but it's about time to have something newer, so we've just
upgraded them to Ubuntu 18.04 (bionic).
This will upgrade old-fashioned to match.

Upgrade build environment to Bionic

---

scripts/ubuntu-bartender/ubuntu-bartender

This solves a problem that came up when my primary disk was close to full, and bartender was building the `ingredients.tar.gz` file (which can be quite large) in my home directory, and then getting errors because my disk was full. This additional argument allows the user to specify another directory (accessible by the strictly-confined multipass snap, e.g. another drive mounted somewhere in the home dir) in which to build the ingredients file.

Add a parameter to bartender to specify where the temp dir should be

---

old-fashioned-image-build

The launchpad-buildd supports a `--proposed` flag, and oftentimes it is desirable to do old-fashioned builds against -proposed. As far as I can tell, enabling this amounts to overriding the sources list (thanks John) and passing the flag down to the `buildlivefs` launchpad-buildd in-target operation.
I've tested these changes by building the xenial azure-base target with bartender. I modified the Makefile in secret sauce to explicitly pass the `--proposed` flag as an `old_fashioned_flags` append. I've verified that the package versions in the resulting manifest are from -proposed where expected.

Enable building from -proposed with old-fashioned

---

scripts/ubuntu-bartender/aws-provider
scripts/ubuntu-bartender/ubuntu-bartender

I've tested this in practice using the aws provider by building a bartender build, in this case of the azure-base project of xenial.
Prior to this change, the commands to ssh and scp in the aws-provider were failing to connect to the instance.
I ran my test build using the default $USER -named key, i.e. I did not specify --aws-keypair-name in the bartender build.

Populate aws key variable down to aws-provider scripts

---

scripts/ubuntu-bartender/README.md
scripts/ubuntu-bartender/multipass-provider
scripts/ubuntu-bartender/ubuntu-bartender
scripts/ubuntu-bartender/ubuntu-hirsute-bartender

1. use the daily bionic image instead; xenial is about EOL and do not have arm64 image.
2. add customizable options `MULTIPASS_DISK_SIZE` and `MULTIPASS_MEM_SIZE` for Multipass provider.
3. include a hirsute provider.

Update on Multipass providers

---

old-fashioned-image-build

Using b2eb76b and trying to build an hirsute desktop ISO with squid-deb-proxy configured as hinted in the instruction the build fails
* Downloading http://people.canonical.com/~ubuntu-archive/seeds/ubuntu.hirsute/STRUCTURE
! Could not open (any of):
!   http://people.canonical.com/~ubuntu-archive/seeds/ubuntu.hirsute/STRUCTURE
It's probably because the deb proxy shouldn't be used for non apt requests? The proposed change fixes the build while still having debs downloaded from the local proxy
launchpad-buildd uses the same http_proxy value to set LB_APT_HTTP_PROXY which is needed to get the live-build created chroot environments to use the apt proxy so setting that one through lxc instead

Don't use the apt proxy for other things

---

scripts/ubuntu-bartender/README.md
scripts/ubuntu-bartender/aws-provider
scripts/ubuntu-bartender/ubuntu-bartender

To generate arm instances before, users would have to manually change
the aws instance type (when building on aws). Added a flag for
AWS_INSTANCE_TYPE to set via config. A wrapper flag to set safe defaults
for aws arm builds was also added.

Add arm configuration

---

.gitignore
scripts/ubuntu-bartender/README.md

When custom hooks are needed, it's useful to know that there is a
`--hook-extras-dir` option that can be used.

README: add example how to use a local hooks dir

---

scripts/ubuntu-bartender/ubuntu-impish-bartender

Impish Indri is the 21.10 codename for the next Ubuntu release so add
a symlink similar to the other symlinks for previous releases.

add ubuntu-bartender symlink to ubuntu-impish-bartender

---

scripts/ubuntu-bartender/ubuntu-bartender

--aws-arm-build shorthand setup aws information, however, can be called
without --build-provider. since the default build provider is now
multipass, this can lead to issues. Now when using the shorthard
--aws-arm-build, BUILD_PROVIDER will be set to "aws" by default.

aws-arm-build only on aws

---

scripts/ubuntu-bartender/ubuntu-bartender

ubuntu-old-fashioned moved from https://github.com/chrisglass/ to
https://github.com/ubuntu-bartenders/ . Use the new URL in the
ubuntu-bartender script.

ubuntu-bartender: fix github url

---

scripts/ubuntu-bartender/ubuntu-bartender

The old default of 8G was likely set on the assumption that all
developers have at least 16G of memory. As a result, running
Bartender w/ Multipass on a 12G (~11.5 working) system concurrent
with a few normal processes (~5G used) resulted in an OutOfMemory
crash (8G+5G=13G > 11.5G). By capping the memory at 50%, 16G
systems can still cap multipass at ~8G, but systems with less
RAM do not run a high risk of an OutOfMemory crash.

Cap default multipass memory usage to 50%

---

scripts/ubuntu-bartender/README.md
scripts/ubuntu-bartender/azure-provider
scripts/ubuntu-bartender/ubuntu-bartender

Because why not?
It can be actually useful to avoid having to upload Azure images (30GB, sparse) from my personal laptop to my Azure storage account. If using `--no-cleanup`, then connecting to the VM when the build is done, one can directly upload the images from Azure to Azure.

Add Azure as build provider

---

old-fashioned-image-build

The repo moved from bzr to git[0] so cloning the code need to use git
now.
[0]
https://lists.ubuntu.com/archives/ubuntu-release/2021-August/005264.html

Fix ubuntu-archive-tools checkout

---

scripts/ubuntu-bartender/ubuntu-bartender

By default this is empty
```
--hook-extras-sbom-repo "${YOUR_SBOM_TOOLS_REPO}" \
--hook-extras-sbom-branch "main"
--hook-extras-sbom-dir "${YOUR_SBOM_TOOLS_REPO_SUBDIRECTORY_TO_NEST}"
```
This means we can iterate and manage this tooling outside of livecd-rootfs or any other extras repos

feat: Add flag to nest sbom tools in */hooks.d/extra/sbom-tools directory

---

scripts/ubuntu-bartender/multipass-provider

This fixes:
warning: "--mem" long option will be deprecated in favour of \
"--memory" in a future release.Please update any scripts, etc.

Fix deprecation warning for multipass provider

---

scripts/ubuntu-bartender/README.md
scripts/ubuntu-bartender/gce-provider
scripts/ubuntu-bartender/ubuntu-bartender

* Previously most of the values for GCE were fixed, meaning some local hacking was needed to build ARM on GCE. Swapping 
these defaults out for variables you can set is a better option going forward.
* Also added a quick flag to build ARM on GCE using defaults, similar to what we have already in AWS.

feat: Add ARM64 builds for GCE

---

setup-old-fashioned

#86 migrated to focal but the setup-old-fashioned utility didn't get updated to accept that serie
it isn't enough to make the script work though since it tries to install 'oldfashioned' from http://ppa.launchpad.net/cloud-images/old-fashioned/ubuntu which seems to not exist anymore?

Setting up old fashioned on focal is allowed now

---

old-fashioned-image-build

launchpad-buildd buildlivefs does accept a "--debug" flag[0] which writes each command to standard error (preceded by a '+') before it is executed. That's very useful for debugging so add the possibility to pass this flag down to launchpad-buildd.
[0]
https://git.launchpad.net/launchpad-buildd/tree/lpbuildd/target/build_livefs.py#n106

Add --debug to old-fashioned-image-build

---

scripts/ubuntu-bartender/README.md
scripts/ubuntu-bartender/ubuntu-bartender

We migrated over to building with focal a few months ago now, but a couple of the GCE docs/comments were left behind and referring to bionic.

fix(docs): Change incorrect references to bionic

---

scripts/ubuntu-bartender/ubuntu-bartender

--hook-extras-sbom-tools-dir was different than all the other *-dir flags, in that it didn't indicate a local checkout/directory to nest into bartender, but instead indicated a subdirectory of an sbom-tool to nest. This made usage unclear. Separated sbom-tools-subdir and sbom-tools-dir into separate params, following the same convention as other *-dir params.
Further the description for the -dir mentioned it was useful. It's not useful, it's a strict requirement to pass when building Canonical Public Cloud projects that create an SBOM. this is due to the code that generates the sbom, at this time, referencing the __init__.py in the cpc-sbom tool. The project is a separate src Python style, so the __init__.py lives in a nested directory. To run CPC builds, one must pass in the var, with a …

fix[#91]: sbom-tools match flag convention and default

---

old-fashioned-image-build
scripts/ubuntu-bartender/ubuntu-bartender

Use `LIVE_BUILD_DIR` environment variable or `--live-build-dir` option to pass in your own live-build local directory
Use `LIVE_BUILD_REPO` and `LIVE_BUILD_BRANCH` environment variables or `--live-build-repo` and `--live-build-branch` options to pass in your own live-build git repo and branch.
This is very useful for being able to debug live-build.

feat: Add ability to inject your own livebuild from git or local directory

---

scripts/ubuntu-bartender/ubuntu-bartender
setup-old-fashioned

This enables testing of MAAS (https://maas.io/) image builds using ubuntu-old-fashioned
usage:
```
--hook-maas-images-repo "https://git.launchpad.net/maas-images"
--hook-maas-images-branch "master"
```
These flags are optional

feat: Add new flags to nest MAAS images code during image build

---

scripts/ubuntu-bartender/README.md

Removing the  `azure-pubkey-path` option documentation, since it is not a valid option.
New SSH keypairs are generated on each run

Document update of Azure build provider options

---

scripts/ubuntu-bartender/ubuntu-bartender

AWS_PROFILE is currently forcibly set to default. It can be overwritten
by the --aws-profile flag. But that requires other scripts that use this
script to support passing --aws-profile. Instead of modyfing these other
scripts, pick the AWS_PROFILE from environment and set it to default
only when it's empty or unset.

Pick AWS_PROFILE from environment

---

scripts/ubuntu-bartender/aws-provider

not all aws cli calls passed in AWS_PROFILE. this will lead to commands failing and instances continuing to run. Checks for instance_running and temrinate_instance will fail to find the instance-ids

fix(AWS): Ensure AWS_PROFILE used in all calls

---

setup-old-fashioned

The last option #6 in the livecd-rootfs menu is none, a choice that I use as I'm just bringing in the copy I want already.  subprocess.call() doesn't like that empty command array.

fix(setup): handle none choice for livecd-rootfs

---

old-fashioned-image-build
scripts/ubuntu-bartender/ubuntu-bartender
setup-old-fashioned

Currently, all cloud providers use 20.04 images
for image build. Since focal will reach EOL in
May, the focal image should be transitioned to
other supported OS versions.
Since the Launchpad builders mostly use 24.04,
switch to noble images to match the builder's
OS version.

fix: Transition to 24.04 images for build
